apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: supplychain-vaultkubenertes-job
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: supplychain-vaultkubenertes-job
  chart:
    git: git@github.com:snyfe/bevel.git
    ref: develop
    path: examples/supplychain-app/charts/vault_kubernetes
  values:
    metadata:
      name: supplychain
      component_type: orderer
      namespace: supplychain-net    
      images:
        alpineutils: hub.docker.com/u/snyfe/alpine-utils:1.0

    vault:
      reviewer_service: vault-reviewer
      role: vault-role
      address: http://10.1.0.35:8200
      authpath: devsupplychain-net-auth
      policy: vault-crypto-orderer-supplychain-net-ro
      secret_path: secretsv2
      serviceaccountname: vault-auth
      imagesecretname: regcred
    
    k8s:
      kubernetes_url: https://kubernetes.docker.internal:6443
